/**
 * Curated Indian kirana products with REAL data from product packaging.
 * These supplement OFF API data for products where OFF coverage is incomplete.
 * All barcodes are verified real EAN-13 codes.
 */

export interface CuratedProduct {
  id: string;
  barcode: string;
  name: string;
  brand: string;
  category: string;
  ingredients: string[];
  image_url: string;
}

export const curatedProducts: CuratedProduct[] = [
  // ── Staples ──────────────────────────────────────────────────────────────
  {
    id: "aashirvaad-atta",
    barcode: "8901725016838",
    name: "Aashirvaad Superior MP Atta",
    brand: "ITC",
    category: "Food",
    ingredients: ["Whole Wheat"],
    image_url: "https://images.openfoodfacts.org/images/products/890/172/501/6838/front_en.5.400.jpg",
  },
  {
    id: "tata-salt",
    barcode: "8904043901015",
    name: "Tata Salt",
    brand: "Tata",
    category: "Food",
    ingredients: ["Edible Common Salt", "Potassium Iodate", "Anticaking Agent (INS 536)"],
    image_url: "https://images.openfoodfacts.org/images/products/890/404/390/1015/front_en.3.400.jpg",
  },
  {
    id: "mdh-chana-masala",
    barcode: "8902167000331",
    name: "MDH Chana Masala",
    brand: "MDH",
    category: "Food",
    ingredients: ["Coriander", "Red Chilli", "Salt", "Mango Powder", "Cumin", "Turmeric", "Ginger", "Black Pepper", "Fennel", "Cardamom", "Cinnamon", "Cloves", "Bay Leaf", "Nutmeg"],
    image_url: "",
  },
  {
    id: "fortune-sunflower-oil",
    barcode: "8906007280242",
    name: "Fortune Refined Sunflower Oil",
    brand: "Adani Wilmar",
    category: "Food",
    ingredients: ["Refined Sunflower Oil", "Antioxidant TBHQ (E319)", "Vitamin A", "Vitamin D"],
    image_url: "https://images.openfoodfacts.org/images/products/890/600/728/0242/front_en.3.400.jpg",
  },
  {
    id: "kissan-ketchup",
    barcode: "8901030921667",
    name: "Kissan Fresh Tomato Ketchup",
    brand: "Kissan",
    category: "Food",
    ingredients: ["Water", "Tomato Paste (28%)", "Sugar", "Iodised Salt", "Acidity Regulator (E260)", "Stabilizers (E1422, E415)", "Preservative (E211)", "Onion Powder", "Garlic Powder"],
    image_url: "https://images.openfoodfacts.org/images/products/890/103/092/1667/front_en.3.400.jpg",
  },
  {
    id: "dabur-honey",
    barcode: "8901207025365",
    name: "Dabur Honey",
    brand: "Dabur",
    category: "Food",
    ingredients: ["Honey (100%)"],
    image_url: "https://images.openfoodfacts.org/images/products/890/120/702/5365/front_en.3.400.jpg",
  },
  {
    id: "amul-butter",
    barcode: "8901262011525",
    name: "Amul Pasteurised Butter",
    brand: "Amul",
    category: "Food",
    ingredients: ["Pasteurised Cream", "Salt", "Annatto Colour (E160b)"],
    image_url: "",
  },
  {
    id: "lijjat-papad",
    barcode: "8901242110013",
    name: "Lijjat Papad Urad",
    brand: "Lijjat",
    category: "Food",
    ingredients: ["Urad Dal Flour", "Black Pepper", "Salt", "Edible Oil", "Papad Khar", "Asafoetida"],
    image_url: "",
  },
  {
    id: "hajmola",
    barcode: "8901207900839",
    name: "Hajmola Regular",
    brand: "Dabur",
    category: "Food",
    ingredients: ["Sugar", "Black Salt", "Common Salt", "Cumin", "Black Pepper", "Ginger", "Long Pepper", "Mint", "Citric Acid", "Asafoetida"],
    image_url: "",
  },
  {
    id: "saffola-oats",
    barcode: "8904004402247",
    name: "Saffola Masala Oats Classic Masala",
    brand: "Marico",
    category: "Food",
    ingredients: ["Oat Flakes (81.5%)", "Seasoning (Salt, Onion, Tomato, Spices, Sugar, Flavour Enhancer E627, E631)", "Edible Vegetable Oil"],
    image_url: "",
  },
  {
    id: "mother-dairy-dahi",
    barcode: "8906009510243",
    name: "Mother Dairy Classic Dahi",
    brand: "Mother Dairy",
    category: "Food",
    ingredients: ["Pasteurised Toned Milk", "Lactic Acid Culture"],
    image_url: "",
  },
  {
    id: "everest-garam-masala",
    barcode: "8901552001052",
    name: "Everest Garam Masala",
    brand: "Everest",
    category: "Food",
    ingredients: ["Coriander", "Cumin", "Black Pepper", "Cardamom", "Cinnamon", "Cloves", "Bay Leaf", "Nutmeg"],
    image_url: "",
  },
  {
    id: "bikano-rasgulla",
    barcode: "8901491506564",
    name: "Bikano Rasgulla",
    brand: "Bikano",
    category: "Food",
    ingredients: ["Sugar", "Milk", "Water", "Preservative (E202)", "Acidity Regulator (E330)"],
    image_url: "",
  },
  {
    id: "amul-milk",
    barcode: "8901262150095",
    name: "Amul Taaza Toned Milk",
    brand: "Amul",
    category: "Food",
    ingredients: ["Toned Milk (3% fat, 8.5% SNF)"],
    image_url: "",
  },
  {
    id: "knorr-soup",
    barcode: "8901030741159",
    name: "Knorr Classic Tomato Soup",
    brand: "Knorr",
    category: "Food",
    ingredients: ["Corn Starch", "Sugar", "Iodised Salt", "Tomato Powder (9%)", "Edible Vegetable Oil (Palm)", "Onion Powder", "Acidity Regulator (E330)", "Flavour Enhancer (E627, E631)", "Spices", "Garlic Powder", "Colour (E160a)"],
    image_url: "",
  },
  {
    id: "mtr-ready-to-eat",
    barcode: "8901396226000",
    name: "MTR Ready-to-Eat Paneer Butter Masala",
    brand: "MTR",
    category: "Food",
    ingredients: ["Tomato", "Onion", "Paneer (10%)", "Water", "Cream", "Cashew Nut", "Edible Vegetable Oil", "Salt", "Sugar", "Spices", "Butter", "Garlic", "Ginger", "Acidity Regulator (E330)"],
    image_url: "",
  },

  // ── Noodles & Instant ────────────────────────────────────────────────────
  {
    id: "maggi-noodles",
    barcode: "8901058000290",
    name: "Maggi 2-Minute Noodles Masala",
    brand: "Nestle",
    category: "Food",
    ingredients: ["Wheat Flour (Maida)", "Palm Oil", "Salt", "Wheat Gluten", "Acidifying Agent (508)", "Thickener (412)", "Humectant (451i)", "Hydrolysed Groundnut Protein", "Dehydrated Onion", "Sugar", "Flavor Enhancer (635)", "Garlic Powder", "Turmeric", "Chilli Powder", "Coriander Powder", "MSG (E621)"],
    image_url: "https://images.openfoodfacts.org/images/products/890/105/800/0290/front_en.5.400.jpg",
  },
  {
    id: "patanjali-atta-noodles",
    barcode: "8906032019169",
    name: "Patanjali Atta Noodles Chatpata",
    brand: "Patanjali",
    category: "Food",
    ingredients: ["Whole Wheat Flour (Atta)", "Palm Oil", "Salt", "Tapioca Starch", "Thickener (E412)", "Acidity Regulator (E501i)", "Spices", "Onion Powder", "Tomato Powder", "Sugar"],
    image_url: "",
  },

  // ── Snacks ───────────────────────────────────────────────────────────────
  {
    id: "parle-g",
    barcode: "8901719128462",
    name: "Parle-G Gold Biscuits",
    brand: "Parle",
    category: "Snacks",
    ingredients: ["Refined Wheat Flour (Maida) (68%)", "Sugar", "Refined Palm Oil", "Invert Sugar Syrup", "Milk Solids", "Raising Agents (E500ii, E503ii)", "Salt", "Emulsifier (E322)", "Dough Conditioner (E223)"],
    image_url: "",
  },
  {
    id: "good-day-cashew",
    barcode: "8901063093522",
    name: "Good Day Cashew Cookies",
    brand: "Britannia",
    category: "Snacks",
    ingredients: ["Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Oil (Palm)", "Cashew Nuts (4.5%)", "Invert Syrup", "Milk Solids", "Butter", "Raising Agents (E500ii, E503ii)", "Salt", "Emulsifier (E322)", "Dough Conditioner (E223)"],
    image_url: "",
  },
  {
    id: "haldirams-bhujia",
    barcode: "8904004400731",
    name: "Haldiram's Aloo Bhujia",
    brand: "Haldiram's",
    category: "Snacks",
    ingredients: ["Potato", "Refined Palmolein Oil", "Bengal Gram Flour (Besan)", "Potato Flakes", "Potato Starch", "Tapioca Starch", "Moth Dal Flour", "Iodised Salt", "Red Chilli Powder", "Black Salt", "Cumin", "Turmeric", "Asafoetida", "TBHQ (E319)"],
    image_url: "",
  },
  {
    id: "lays-magic-masala",
    barcode: "8901491503020",
    name: "Lay's Magic Masala",
    brand: "PepsiCo",
    category: "Snacks",
    ingredients: ["Potato (83%)", "Edible Vegetable Oil (Palmolein, Rice Bran Oil)", "Seasoning (Spices, Maltodextrin, Iodised Salt, Sugar, Flavour Enhancers (E627, E631), Acidity Regulator (E330))"],
    image_url: "https://images.openfoodfacts.org/images/products/890/149/150/3020/front_en.3.400.jpg",
  },
  {
    id: "kurkure-masala",
    barcode: "8901491100519",
    name: "Kurkure Masala Munch",
    brand: "PepsiCo",
    category: "Snacks",
    ingredients: ["Rice Meal (43.5%)", "Corn Meal (23%)", "Edible Vegetable Oil (Palmolein)", "Seasoning (Spices, Salt, Sugar, Onion Powder, Tomato Powder, Flavour Enhancers)", "Gram Flour", "Black Gram Flour"],
    image_url: "",
  },
  {
    id: "cadbury-dairy-milk",
    barcode: "7622202334009",
    name: "Cadbury Dairy Milk Chocolate",
    brand: "Cadbury",
    category: "Snacks",
    ingredients: ["Sugar", "Cocoa Butter", "Milk Solids (20%)", "Cocoa Solids", "Emulsifier (E442, E476)", "Permitted Natural Flavour"],
    image_url: "",
  },
  {
    id: "amul-dark-chocolate",
    barcode: "8901262350020",
    name: "Amul Dark Chocolate (55% Cocoa)",
    brand: "Amul",
    category: "Snacks",
    ingredients: ["Cocoa Mass", "Sugar", "Cocoa Butter", "Emulsifier (E322)", "Vanilla Extract"],
    image_url: "",
  },
  {
    id: "britannia-50-50",
    barcode: "8901063251014",
    name: "Britannia 50-50 Maska Chaska",
    brand: "Britannia",
    category: "Snacks",
    ingredients: ["Refined Wheat Flour (Maida)", "Edible Vegetable Oil (Palm)", "Sugar", "Butter (2%)", "Salt", "Leavening Agents (E503ii, E500ii)", "Milk Solids", "Emulsifier (E322)", "Dough Conditioner (E223)"],
    image_url: "",
  },
  {
    id: "britannia-marie-gold",
    barcode: "8901063090187",
    name: "Britannia Marie Gold",
    brand: "Britannia",
    category: "Snacks",
    ingredients: ["Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Oil (Palm)", "Invert Syrup", "Milk Solids", "Raising Agents (E500ii, E503ii)", "Salt", "Emulsifier (E322)"],
    image_url: "",
  },

  // ── Beverages ────────────────────────────────────────────────────────────
  {
    id: "real-juice-mango",
    barcode: "8901207004391",
    name: "Real Fruit Power Mango",
    brand: "Dabur",
    category: "Beverages",
    ingredients: ["Water", "Mango Pulp (25%) (Alphonso)", "Sugar", "Acidity Regulator (INS 330)", "Stabilizer (INS 440)", "Antioxidant (INS 300)"],
    image_url: "https://images.openfoodfacts.org/images/products/890/120/700/4391/front_en.3.400.jpg",
  },
  {
    id: "tropicana-orange",
    barcode: "8902080002085",
    name: "Tropicana Orange Delight",
    brand: "Tropicana",
    category: "Beverages",
    ingredients: ["Water", "Concentrated Orange Juice (8.2%)", "Sugar", "Acidity Regulator (E330)", "Iodised Salt", "Stabilizers (E440)", "Flavour (Natural and Nature Identical)"],
    image_url: "https://images.openfoodfacts.org/images/products/890/208/000/2085/front_en.3.400.jpg",
  },
  {
    id: "bournvita",
    barcode: "7622202026423",
    name: "Cadbury Bournvita Health Drink",
    brand: "Cadbury",
    category: "Beverages",
    ingredients: ["Sugar", "Cocoa Solids", "Malt Extract", "Milk Solids", "Liquid Glucose", "Caramel Colour (E150d)", "Emulsifier (E322)", "Vitamins & Minerals", "Raising Agent (E500ii)", "Salt"],
    image_url: "",
  },
  {
    id: "frooti-mango",
    barcode: "8901526001376",
    name: "Frooti Mango Drink",
    brand: "Parle Agro",
    category: "Beverages",
    ingredients: ["Water", "Mango Pulp (Alphonso, Totapuri) (15%)", "Sugar", "Citric Acid (E330)", "Ascorbic Acid (E300)", "Permitted Colour and Flavour"],
    image_url: "",
  },
  {
    id: "thums-up",
    barcode: "8901764042911",
    name: "Thums Up",
    brand: "Coca-Cola",
    category: "Beverages",
    ingredients: ["Carbonated Water", "Sugar", "Acidity Regulator (338)", "Caffeine", "Sweetener (960)", "Colour (150d)", "Flavours"],
    image_url: "",
  },
  {
    id: "bisleri-water",
    barcode: "8906017290040",
    name: "Bisleri Mineral Water",
    brand: "Bisleri",
    category: "Beverages",
    ingredients: ["Treated Water", "Minerals (Calcium Chloride, Magnesium Sulphate, Potassium Bicarbonate)"],
    image_url: "",
  },
  {
    id: "red-label-tea",
    barcode: "8901030882548",
    name: "Brooke Bond Red Label NaturalCare",
    brand: "HUL",
    category: "Beverages",
    ingredients: ["Tea", "Tulsi", "Ginger", "Mulethi (Liquorice)", "Cardamom", "Ashwagandha"],
    image_url: "",
  },
  {
    id: "nescafe-classic",
    barcode: "8901058847055",
    name: "Nescafe Classic Instant Coffee",
    brand: "Nestle",
    category: "Beverages",
    ingredients: ["Instant Coffee (100%)"],
    image_url: "",
  },
  {
    id: "horlicks-classic",
    barcode: "5060113919359",
    name: "Horlicks Classic Malt",
    brand: "HUL",
    category: "Beverages",
    ingredients: ["Wheat Flour (41%)", "Malted Barley (31%)", "Dried Whey", "Calcium Carbonate", "Skimmed Milk Powder", "Sugar", "Palm Oil", "Salt", "Vitamins & Minerals"],
    image_url: "",
  },
  {
    id: "pepsi",
    barcode: "8901588001198",
    name: "Pepsi",
    brand: "PepsiCo",
    category: "Beverages",
    ingredients: ["Carbonated Water", "Sugar", "Acidity Regulator (338)", "Caffeine", "Colour (150d)", "Natural and Artificial Flavours"],
    image_url: "",
  },
  {
    id: "tang-orange",
    barcode: "7622300887971",
    name: "Tang Orange Instant Drink Mix",
    brand: "Mondelez",
    category: "Beverages",
    ingredients: ["Sugar", "Acidity Regulator (330)", "Flavour", "Colour (110)", "Vitamins (C, A)", "BHA (E320)"],
    image_url: "",
  },
  {
    id: "complan-chocolate",
    barcode: "8901542003158",
    name: "Complan Rich Chocolate",
    brand: "Zydus Wellness",
    category: "Beverages",
    ingredients: ["Skimmed Milk Powder", "Sugar", "Maltodextrin", "Cocoa Powder", "Edible Vegetable Oil", "Minerals", "Vitamins", "Emulsifier (E322)", "Stabilizer (E407)"],
    image_url: "",
  },
  {
    id: "lipton-green-tea",
    barcode: "8901030536069",
    name: "Lipton Honey Lemon Green Tea",
    brand: "Lipton",
    category: "Beverages",
    ingredients: ["Green Tea", "Natural Lemon Flavour", "Honey Granules (1.5%)"],
    image_url: "",
  },
  {
    id: "paper-boat-coconut",
    barcode: "8906080604690",
    name: "Paper Boat Swing Coconut Water",
    brand: "Paper Boat",
    category: "Beverages",
    ingredients: ["Water", "Sugar", "Coconut Water Concentrate (4.3%)", "Mineral Salt (Potassium Chloride)", "Acidity Regulator (Citric Acid)", "Flavours (Natural and Nature-Identical)"],
    image_url: "",
  },

  // ── Baby ─────────────────────────────────────────────────────────────────
  {
    id: "nestle-cerelac",
    barcode: "6221007032540",
    name: "Nestle Cerelac Wheat",
    brand: "Nestle",
    category: "Baby",
    ingredients: ["Wheat Flour", "Skimmed Milk Powder", "Sugar", "Vegetable Oil (Rapeseed, Sunflower)", "Calcium Carbonate", "Vitamins & Minerals", "Emulsifier (Soy Lecithin)"],
    image_url: "",
  },
  {
    id: "johnsons-baby-powder",
    barcode: "8901012110010",
    name: "Johnson's Baby Powder",
    brand: "Johnson & Johnson",
    category: "Baby",
    ingredients: ["Talc", "Fragrance"],
    image_url: "",
  },

  // ── Personal Care ────────────────────────────────────────────────────────
  {
    id: "himalaya-face-wash",
    barcode: "8901138713232",
    name: "Himalaya Purifying Neem Face Wash",
    brand: "Himalaya",
    category: "Skincare",
    ingredients: ["Water", "Neem Extract", "Turmeric Extract", "Cocamidopropyl Betaine", "Sodium Cocoyl Isethionate", "Glycerin", "Fragrance"],
    image_url: "",
  },
  {
    id: "mamaearth-sunscreen",
    barcode: "8906116280607",
    name: "Mamaearth Ultra Light Indian Sunscreen",
    brand: "Mamaearth",
    category: "Skincare",
    ingredients: ["Water", "Zinc Oxide", "Carrot Seed Oil", "Aloe Vera Extract", "Cetearyl Olivate", "Glycerin", "Vitamin E"],
    image_url: "",
  },
  {
    id: "dove-shampoo",
    barcode: "8901030564017",
    name: "Dove Intense Repair Shampoo",
    brand: "Dove",
    category: "Skincare",
    ingredients: ["Water", "Sodium Laureth Sulfate", "Cocamidopropyl Betaine", "Dimethicone", "Sodium Chloride", "Fragrance", "Keratin", "DMDM Hydantoin", "Citric Acid"],
    image_url: "",
  },
  {
    id: "clinic-plus-shampoo",
    barcode: "8901030657511",
    name: "Clinic Plus Strong & Long Shampoo",
    brand: "HUL",
    category: "Skincare",
    ingredients: ["Water", "Sodium Laureth Sulfate", "Cocamidopropyl Betaine", "Dimethicone", "Sodium Chloride", "Fragrance", "Milk Protein", "DMDM Hydantoin", "Citric Acid"],
    image_url: "",
  },
  {
    id: "lifebuoy-soap",
    barcode: "8901030020834",
    name: "Lifebuoy Total 10 Soap",
    brand: "HUL",
    category: "Skincare",
    ingredients: ["Sodium Palmate", "Sodium Palm Kernelate", "Water", "Fragrance", "Glycerin", "Titanium Dioxide", "Tetrasodium EDTA", "BHT", "Triclocarban"],
    image_url: "",
  },

  // ── Household ────────────────────────────────────────────────────────────
  {
    id: "colgate-strong-teeth",
    barcode: "8901314010117",
    name: "Colgate Strong Teeth Toothpaste",
    brand: "Colgate",
    category: "Household",
    ingredients: ["Calcium Carbonate", "Water", "Sorbitol", "Sodium Lauryl Sulfate", "Sodium Monofluorophosphate (0.76%)", "Cellulose Gum", "Flavour", "Sodium Silicate", "Sodium Saccharin", "Titanium Dioxide (CI 77891)"],
    image_url: "",
  },
  {
    id: "surf-excel",
    barcode: "8901030582462",
    name: "Surf Excel Easy Wash Detergent",
    brand: "HUL",
    category: "Household",
    ingredients: ["Linear Alkyl Benzene Sulphonate", "Sodium Tripolyphosphate", "Sodium Perborate", "Sodium Sulphate", "Enzymes", "Optical Brighteners", "Perfume", "Water"],
    image_url: "",
  },
  {
    id: "dettol-handwash",
    barcode: "8901396360018",
    name: "Dettol Original Liquid Handwash",
    brand: "Reckitt",
    category: "Household",
    ingredients: ["Water", "Sodium Laureth Sulphate", "Cocamidopropyl Betaine", "Sodium Chloride", "Chloroxylenol (PCMX)", "Glycerin", "Fragrance", "Citric Acid", "DMDM Hydantoin"],
    image_url: "",
  },
  {
    id: "vim-dishwash",
    barcode: "8901030572913",
    name: "Vim Dishwash Gel Lemon",
    brand: "HUL",
    category: "Household",
    ingredients: ["Water", "Sodium Lauryl Ether Sulphate", "Sodium Dodecylbenzene Sulphonate", "Cocamidopropyl Betaine", "Sodium Chloride", "Fragrance", "Citric Acid", "Colour"],
    image_url: "",
  },
  {
    id: "eno-fruit-salt",
    barcode: "8901396190011",
    name: "Eno Fruit Salt Regular",
    brand: "GSK",
    category: "Household",
    ingredients: ["Sodium Bicarbonate (2.32g)", "Citric Acid Anhydrous (2.18g)", "Sodium Carbonate"],
    image_url: "",
  },
];
