#!/usr/bin/env bash
# Generate a release-signing keystore for the Sift Android app.
#
# Run ONCE per app — the keystore identity is permanent. Losing this file
# means losing the ability to push updates to the same Play Store listing,
# so back it up to a password manager / secure cloud storage immediately
# after creation.
#
# Usage:
#   npm run android:keystore
#
# What this does:
#   1. Prompts for keystore + key passwords (stored only in keystore.properties).
#   2. Runs keytool to generate ./android/app/sift-release.keystore.
#   3. Writes android/keystore.properties for Gradle to read.
#   4. Adds both files to .gitignore (idempotent).
#
# DOES NOT do:
#   - Upload to Play Console (manual: https://play.google.com/console)
#   - Push the keystore anywhere — that's your job, securely.

set -euo pipefail

KEYSTORE_DIR="android/app"
KEYSTORE_FILE="${KEYSTORE_DIR}/sift-release.keystore"
PROPS_FILE="android/keystore.properties"
ALIAS="sift-release"

if [[ ! -d android ]]; then
  echo "❌ android/ directory not found."
  echo "   Run: npm run cap:add:android"
  exit 1
fi

if [[ -f "$KEYSTORE_FILE" ]]; then
  echo "⚠️  Keystore already exists at $KEYSTORE_FILE."
  echo "   If you re-create it the Play Store will reject your next upload."
  echo "   Continue ONLY if you know this is a fresh app with no Play listing."
  read -r -p "Type 'I understand' to continue: " CONFIRM
  if [[ "$CONFIRM" != "I understand" ]]; then
    echo "Aborted."
    exit 1
  fi
  rm -f "$KEYSTORE_FILE" "$PROPS_FILE"
fi

echo ""
echo "→ Generating keystore at $KEYSTORE_FILE"
echo ""
echo "You'll be asked for:"
echo "  - Keystore password (you'll set this twice)"
echo "  - Key password (can be the same)"
echo "  - Distinguished Name fields (CN, OU, O, L, ST, C)"
echo ""
echo "Use real values — Play Store reviewers can see the CN."
echo ""

read -r -s -p "Keystore password (stored locally only): " KEYSTORE_PASS
echo
read -r -s -p "Confirm keystore password: " KEYSTORE_PASS_CONFIRM
echo
if [[ "$KEYSTORE_PASS" != "$KEYSTORE_PASS_CONFIRM" ]]; then
  echo "❌ Passwords do not match."
  exit 1
fi
read -r -s -p "Key password (press Enter to reuse keystore password): " KEY_PASS
echo
KEY_PASS=${KEY_PASS:-$KEYSTORE_PASS}

keytool -genkey -v \
  -keystore "$KEYSTORE_FILE" \
  -alias "$ALIAS" \
  -keyalg RSA -keysize 2048 -validity 10000 \
  -storepass "$KEYSTORE_PASS" \
  -keypass "$KEY_PASS"

cat > "$PROPS_FILE" <<EOF
# Auto-generated by scripts/keystore-gen.sh — do not commit this file.
# These values are read by android/app/build.gradle via gradleProperties.
storeFile=app/sift-release.keystore
storePassword=$KEYSTORE_PASS
keyAlias=$ALIAS
keyPassword=$KEY_PASS
EOF

# Idempotent .gitignore additions.
GITIGNORE=".gitignore"
for pattern in "android/app/sift-release.keystore" "android/keystore.properties"; do
  if ! grep -qxF "$pattern" "$GITIGNORE" 2>/dev/null; then
    echo "$pattern" >> "$GITIGNORE"
  fi
done

echo ""
echo "✅ Keystore created at $KEYSTORE_FILE"
echo "✅ Gradle props written to $PROPS_FILE"
echo "✅ Both files added to .gitignore"
echo ""
echo "BACK UP THE KEYSTORE NOW:"
echo "  cp $KEYSTORE_FILE ~/Documents/sift-release-keystore-$(date +%F).keystore"
echo "  Save the password in 1Password / Bitwarden under 'Sift Android signing'."
echo ""
echo "Without the keystore + passwords you cannot push updates to the same"
echo "Play Store listing. Losing them means re-publishing under a new appId."
